### ISSUE TITLE
Bug: AlphaRouter.route returning Error: invalid address on Polygon Mumbai

### ISSUE THREAD

**Issue by shareefhadid** [Uniswap/smart-order-router#490] opened 2024-02-14 23:41 UTC
## **I'm submitting a ...**
  [X] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

## **Summary**
I have been using `AlphaRouter`'s `.route()` method to get routes for my swaps. It was working for me for months. I recently re-deployed, and some dependencies got updated.

Now no matter what tokens I pass in on Polygon Mumbai, I get `Error: invalid address`. I tried using `SWAP_ROUTER_02` and `UNIVERSAL_ROUTER`.

The exact same code works for me locally (unless I delete my `yarn.lock` and reinstall the dependencies).

### Stack trace:
```
Error: invalid address (argument="address", value=undefined, code=INVALID_ARGUMENT, version=address/5.7.0)
    at Logger.makeError (/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at Logger.throwArgumentError (/node_modules/@ethersproject/logger/lib/index.js:250:21)
    at getAddress (/node_modules/@ethersproject/address/lib/index.js:70:16)
    at Object.getCreate2Address (/node_modules/@ethersproject/address/lib/index.js:138:105)
    at computePairAddress (/node_modules/@uniswap/smart-order-router/node_modules/@uniswap/v2-sdk/dist/v2-sdk.cjs.development.js:255:18)
    at Function.getAddress (/node_modules/@uniswap/smart-order-router/node_modules/@uniswap/v2-sdk/dist/v2-sdk.cjs.development.js:266:12)
    at V2PoolProvider.getPoolAddress (/node_modules/@uniswap/smart-order-router/build/main/providers/v2/pool-provider.js:111:43)
    at CachingV2PoolProvider.getPoolAddress (/node_modules/@uniswap/smart-order-router/build/main/providers/v2/caching-pool-provider.js:86:34)
    at CachingV2PoolProvider.getPools (/node_modules/@uniswap/smart-order-router/build/main/providers/v2/caching-pool-provider.js:40:58) {
      reason: 'invalid address',
      code: 'INVALID_ARGUMENT',
      argument: 'address',
      value: undefined
    }
```

From what I see, the v2 SDK is missing Mumbai in the `FACTORY_ADDRESS_MAP`:
```ts
var FACTORY_ADDRESS_MAP = {
  // Mainnet
  1: '0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f',
  // Ropsten
  3: '0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f',
  // Goerli
  5: '0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f',
  // Optimism
  10: '0x0c3c1c532F1e39EdF36BE9Fe0bE1410313E074Bf',
  // Arbitrum
  42161: '0xf1D7CC64Fb4452F05c498126312eBE29f30Fbcf9',
  // Avalanche
  43114: '0x9e5A52f57b3038F1B8EeE45F28b3C1967e22799C',
  // Base
  8453: '0x8909dc15e40173ff4699343b6eb8132c65e18ec6',
  // BNB
  56: '0x8909Dc15e40173Ff4699343b6eB8132c65e18eC6',
  // Polygon
  137: '0x9e5A52f57b3038F1B8EeE45F28b3C1967e22799C'
};
```
Mumbai would be `80001`. This is in `@uniswap/v2-sdk/dist/v2-sdk.cjs.development.js`.

I've spent days trying to debug, that's all I got. If anyone can provide input, it would be greatly appreciated.

**Comment by acinmavi** [comment] 2024-03-28 09:01
I got the same error , do you have any suggestion about how to fix it ?

**Comment by shareefhadid** [comment] 2024-03-28 09:46
> I got the same error , do you have any suggestion about how to fix it ?

I don't seem to have this issue anymore. I updated all my packages to the latest version.

**Comment by acinmavi** [comment] 2024-03-28 10:09
Thanks @shareefhadid 
I updated my packages to the latest version and the problem is gone.
We could close this issue

**Closed** 2024-03-28 13:04 UTC
